version: "3.8"
services:
  web:
    build:
      context: ./client
      target: production
    image: aryankalra363/real-estate-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production

  api:
    build:
      context: .
      target: production
    image: aryankalra363/real-estate-backend
    restart: unless-stopped
    ports:
      - "5000"
