version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./client
    image: aryankalra363/real-estate-frontend
    restart: unless-stopped
    environment:
      - VITE_FIREBASE_API_KEY=${YOUR_VITE_FIREBASE_API_KEY}

  api:
    build: .
    image: aryankalra363/real-estate-backend
    restart: unless-stopped
    environment:
      - PORT=5000
      - DATABASE_URL=${YOUR_DATABASE_URL}
      - JWT_SECRET=${YOUR_JWT_TOKEN}
